# Generated by Django 6.0.1 on 2026-08-11 13:25

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_full_name', models.CharField(max_length=255)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=15)),
                ('amount_deducted', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('bonus', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('date_recieved', models.DateField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('created_by', models.CharField(max_length=200)),
                ('updated_by', models.CharField(max_length=200)),
                ('created_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_salary_created_by_user_id', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.staff')),
                ('updated_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_salary_updated_by_user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
