# Generated by Django 6.0.1 on 2026-08-11 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_staffsalary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffsalary',
            old_name='date_recieved',
            new_name='date_received',
        ),
    ]
