# Generated by Django 6.0.1 on 2026-07-24 12:31

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_staff_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountdetail',
            old_name='bank_full_name',
            new_name='account_name',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='full_name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='staff',
            name='last_name',
            field=models.CharField(default='2026-01-01', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staff',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
    ]
