# Generated by Django 6.0.1 on 2026-07-24 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_role_updated_at_role_updated_by_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='updated_by',
            field=models.CharField(default='2026-01-01', max_length=200),
            preserve_default=False,
        ),
    ]
