# Generated by Django 6.0.1 on 2026-07-14 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='account_details',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='created_by_user',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='updated_by_user',
        ),
        migrations.DeleteModel(
            name='AccountDetails',
        ),
        migrations.DeleteModel(
            name='Salary',
        ),
    ]
