# Generated by Django 6.0.1 on 2026-07-25 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diesel',
            name='date_recorded',
            field=models.DateField(auto_now_add=True, default='2026-07-25'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ekedc',
            name='date_recorded',
            field=models.DateField(auto_now_add=True, default='2026-07-25'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='date_recorded',
            field=models.DateField(auto_now_add=True, default='2026-07-25'),
            preserve_default=False,
        ),
    ]
