# Generated by Django 6.0.1 on 2026-07-17 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0004_diesel_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='ekedc',
            name='kwh',
            field=models.DecimalField(decimal_places=2, default='0.01', max_digits=15),
            preserve_default=False,
        ),
    ]
