# Generated by Django 6.0.1 on 2026-07-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0005_ekedc_kwh'),
    ]

    operations = [
        migrations.AddField(
            model_name='diesel',
            name='transport',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
