# Generated by Django 6.0.1 on 2026-07-17 17:03

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0006_diesel_transport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diesel',
            name='transport',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
    ]
