# Generated by Django 6.0.1 on 2026-07-17 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0007_alter_diesel_transport'),
    ]

    operations = [
        migrations.AddField(
            model_name='diesel',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
            preserve_default=False,
        ),
    ]
