# Generated by Django 6.0.1 on 2026-07-19 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0008_diesel_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
