# Generated by Django 6.0.1 on 2026-07-22 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0010_alter_expense_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='category_name',
            field=models.CharField(default='category', max_length=255),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='expense.category'),
        ),
    ]
