# Generated by Django 6.0.1 on 2026-07-23 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0012_alter_expense_created_at_alter_expense_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diesel',
            name='created_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diesel',
            name='updated_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ekedc',
            name='created_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ekedc',
            name='updated_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='updated_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
