# Generated by Django 6.0.1 on 2026-08-05 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='position',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, to='directors.position'),
            preserve_default=False,
        ),
    ]
